# 世界boss的伤害排名发给谁
# Participant: 参战者
# All: 所有人
# None: 不发
BossDamageRank: "Participant"

# 发送的内容格式
# %boss_name% boss名
# %details% 详情，鼠标悬浮显示
# 支持papi （感觉用不上）
BossDamageMessage: "%boss_name% &f&l已被击败！ %details%"

# 详情的内容格式
# %boss_name% boss名
# %rank% 排名
# %rank_self% 自己的排名
# 第一行为显示在外的内容
BossDamageDetails:
  - "§f§l[查看详情]"
  - "&7&m-------&r &6&l伤害排名 &7&m-------&r"
  # 前面的&7-和后面的&7< 为通用前后缀，会自动添加到rank的每一行前后
  - "&7- %rank% &7<"
  - "&7- &f..."
  - "&7- %rank_self%"
  - "&7&m-------&r &6&l伤害排名 &7&m-------&r"

# 显示前几名
ShowTop: 10

# 每一条伤害排名的格式
# %rank% 排名
# %player% 玩家名
# %damage% 伤害
# %rate% 伤害占比
# 支持papi （感觉用不上）
RankEntry:
  - "&f%rank%. &f%player% &7- &f%damage% (%rate%%)"


# 上方的示例展示效果为：
# 示例boss2 已被击败！ [查看详情]
# (鼠标悬浮在[查看详情]时展示下面的内容)
# ------- 伤害排名 -------
# - 1. 很厉害的玩家 - 500000 (50%)
# - 2. 厉害的玩家 - 250000 (25%)
# - 3. 一般的玩家 - 100000 (10%)
# - 4. 摸鱼玩家 - 10000 (1%)
# - 5. 摸鱼玩家 - 10000 (1%)
# - 6. 摸鱼玩家 - 10000 (1%)
# - 7. 摸鱼玩家 - 10000 (1%)
# - 8. 摸鱼玩家 - 10000 (1%)
# - 9. 摸鱼玩家 - 10000 (1%)
# - 10. 摸鱼玩家 - 10000 (1%)
# - ...
# - 18. 自己 - 5000 (0.5%)
# ------- 伤害排名 -------
