name: MythicBoss
main: icu.xiyoumc.mmboss.MMBoss
author: LunarSilhouette
version: 1.0
api-version: 1.13
depend:
  - MythicMobs
  - PlaceholderAPI
commands:
    mmboss:
        description: MythicBoss的主命令
        usage: /mmboss
        aliases: [boss]